# Generated by Django 4.2.2 on 2023-06-08 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_document"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Document",
            new_name="ProcessedDocument",
        ),
    ]
